[package]
name = "dbus-parsec"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

[dependencies]
dbus = "0.8.4"
dbus-crossroads = "0.2.1"
parsec-client = { version = "0.7.1", features = ["no-fs-permission-check"] }
ring = "0.16.15"

[build-dependencies]
dbus-codegen = "0.5.0"
